### ISSUE TITLE
Optimize assets compilation

### ISSUE THREAD

**Issue by francois2metz** [af83/capistrano-af83-old#1]
We should add this good trick:

``` ruby
namespace :deploy do
  namespace :assets do
    task :precompile, :roles => :web, :except => { :no_release => true } do
      from = source.next_revision(current_revision)
      if capture("cd #{latest_release} && #{source.local.log(from)} vendor/assets/ app/assets/ | wc -l").to_i > 0
        run %Q{cd #{latest_release} && #{rake} RAILS_ENV=#{rails_env} #{asset_env} assets:precompile}
      else
        logger.info "Skipping asset pre-compilation because there were no asset changes"
      end
    end
  end
end
```

http://www.bencurtis.com/2011/12/skipping-asset-compilation-with-capistrano/

**Comment by nono** [comment]
I see a lot of edge cases for this recipe:
- some assets come from gems (jquery, sass, etc.)
- some assets use helpers from outside (compass)
- some JS are generated at each deploy (JS routes)
- some assets use data coming from a database or YAML files (i18n stuff)

So, I'm not sure it's a good idea to add this recipe.
