### ISSUE TITLE
Update for capistrano v3

### ISSUE THREAD

**Issue by spk** [af83/capistrano-af83-old#4]

**Comment by elentras** [comment]
Hi, I tried to setup this gem but I'm getting this error : 

```
Unable to activate capistrano-af83-0.4.5, because capistrano-3.0.1 conflicts with capistrano (~> 2.14)
```

Seems linked to this issue.

**Comment by nono** [comment]
Capistrano 3 is a full rewrite of capistrano 2, and all the plugins for capistrano 2 won't work with capistrano 3. So, it's a lot of work to port capistrano-af83 to capistrano 3 and we haven't done it for the moment.

**Comment by nono** [comment]
I played with capistrano 3, but it seems it's not really mature. For example, the rails integration tries to run rake without `bundle exec`. So, I don't think we will move to capistrano 3 soon.

**Comment by elentras** [comment]
ok, I understand. Thanks !
